/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import data.UsuarioDAO;
import javax.swing.JOptionPane;
import presentacion.ventanas.formAdmin;
import presentacion.ventanas.formVentas;
import roles.SesionUsuario;

/**
 * Pantalla de autenticación principal.
 * Valida credenciales, carga sesión y enruta según rol (admin/cajero).
 */
public class Login extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = 
        java.util.logging.Logger.getLogger(Login.class.getName());

    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
        textoSombra user = new textoSombra("User", txtUser);
        textoSombra password = new textoSombra("Password", psPassword);
        setResizable(false);
        aplicarEstiloMinimo();
    }

    // Pulido visual mínimo de inputs y botones sin modificar el layout generado.
    private void aplicarEstiloMinimo() {
        java.awt.Font labelFont = new java.awt.Font("SansSerif", java.awt.Font.BOLD, 16);
        java.awt.Font inputFont = new java.awt.Font("SansSerif", java.awt.Font.PLAIN, 16);
        java.awt.Color azulPrimario = new java.awt.Color(37, 99, 235);
        java.awt.Color textoOscuro = new java.awt.Color(31, 41, 55);
        java.awt.Color fondoInput = new java.awt.Color(248, 250, 252);
        java.awt.Color bordeInput = new java.awt.Color(203, 213, 225);

        jLabel1.setFont(labelFont);
        jLabel11.setFont(labelFont);
        jLabel3.setForeground(textoOscuro);

        txtUser.setFont(inputFont);
        txtUser.setBackground(fondoInput);
        txtUser.setForeground(textoOscuro);
        txtUser.setCaretColor(textoOscuro);
        txtUser.setBorder(javax.swing.BorderFactory.createCompoundBorder(
                javax.swing.BorderFactory.createLineBorder(bordeInput, 1),
                javax.swing.BorderFactory.createEmptyBorder(6, 10, 6, 10)));

        psPassword.setFont(inputFont);
        psPassword.setBackground(fondoInput);
        psPassword.setForeground(textoOscuro);
        psPassword.setCaretColor(textoOscuro);
        psPassword.setBorder(javax.swing.BorderFactory.createCompoundBorder(
                javax.swing.BorderFactory.createLineBorder(bordeInput, 1),
                javax.swing.BorderFactory.createEmptyBorder(6, 10, 6, 10)));

        btnLogin.setBackground(azulPrimario);
        btnLogin.setBorder(javax.swing.BorderFactory.createEmptyBorder());
        btnLogin.setFocusPainted(false);

        btnSignup1.setBackground(new java.awt.Color(59, 130, 246));
        btnSignup1.setBorder(javax.swing.BorderFactory.createEmptyBorder());
        btnSignup1.setFocusPainted(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        psPassword = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnSignup1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("for Health");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 150, 50));

        jLabel4.setText("Fast • Secure • Reliable");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 740, -1, -1));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("and Everyone´s Well-Being");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 310, 50));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Working Every Day  ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 270, 50));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Welcome!");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 290, 50));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/imagenes/FONDOAZUL.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 560, 860));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/imagenes/healthcare.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 30, 110, 90));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setText("User*");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 170, 90, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel3.setText("HealthPharmacy");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 60, 190, 40));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Login");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 420, 90, 30));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 250, 290, 10));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 350, 290, 10));

        psPassword.setBackground(new java.awt.Color(0, 0, 0,0));
        psPassword.setFont(new java.awt.Font("Segoe UI", 0, 18));
        psPassword.setBorder(null);
        jPanel1.add(psPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 312, 290, 40));

        jLabel11.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel11.setText("Password*");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 270, 110, 40));

        txtUser.setBackground(new java.awt.Color(0, 0, 0, 0));
        txtUser.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        txtUser.setBorder(null);
        jPanel1.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 212, 290, 40));

        btnLogin.setBackground(new java.awt.Color(0, 102, 255));
        btnLogin.addActionListener(this::btnLoginActionPerformed);
        jPanel1.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 410, 140, 50));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Login");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 420, 90, 30));

        jLabel13.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Signup");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 420, -1, -1));

        btnSignup1.setBackground(new java.awt.Color(0, 102, 255));
        btnSignup1.setForeground(new java.awt.Color(255, 255, 255));
        btnSignup1.addActionListener(this::btnSignup1ActionPerformed);
        jPanel1.add(btnSignup1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 410, 140, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 810));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed

        // Captura de credenciales ingresadas en UI.
        String usuario = txtUser.getText();
        String password = new String(psPassword.getPassword());

        if (usuario.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor llena todos los campos",
                    "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            // 1) Autenticar usuario + rol desde base de datos.
            UsuarioDAO usuarioDAO = new UsuarioDAO();
            Object[] auth = usuarioDAO.autenticarConRol(usuario, password);

            if (auth == null) {
                JOptionPane.showMessageDialog(this, "Usuario o contraseña incorrectos",
                        "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            String idUsuario = (String) auth[0];
            String nombreUsuario = (String) auth[1];
            String nombreRol = (String) auth[2];

            // 2) Persistir acceso y guardar sesión en singleton.
            usuarioDAO.actualizarUltimoAcceso(idUsuario);
            SesionUsuario.getInstancia().iniciarSesion(idUsuario, nombreUsuario, nombreRol);

            JOptionPane.showMessageDialog(this, "¡Bienvenido " + nombreUsuario + " (" + nombreRol + ")!");

            // 3) Navegación por rol.
            if ("Administrador".equalsIgnoreCase(nombreRol)) {
                new formAdmin().setVisible(true);
            } else {
                new formVentas().setVisible(true);
            }
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnSignup1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignup1ActionPerformed
        new SingUp().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSignup1ActionPerformed
     public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info :
                    javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(Login.class.getName())
                .log(java.util.logging.Level.SEVERE, null, ex);
        }
        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnSignup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPasswordField psPassword;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}

